### ISSUE TITLE
install script not working

### ISSUE THREAD

**Issue by UltiRequiem** [axetroy/cask.rs#16] opened 2022-03-17 17:44 UTC
It doesn't work with or without sudo.

https://user-images.githubusercontent.com/71897736/158862974-4e183c33-972e-40c7-9978-ef1d41ea7374.mp4

Neofetch

```
                   -`                    z@frame
                  .o+`                   -------
                 `ooo/                   OS: Arch Linux x86_64
                `+oooo:                  Host: HP 250 G7 Notebook PC
               `+oooooo:                 Kernel: 5.16.13-arch1-1
               -+oooooo+:                Uptime: 3 hours, 49 mins
             `/:-:++oooo+:               Packages: 991 (pacman)
            `/++++/+++++++:              Shell: zsh 5.8.1
           `/++++++++++++++:             Resolution: 1366x768, 1600x900
          `/+++ooooooooooooo/`           WM: i3
         ./ooosssso++osssssso+`          Theme: Adwaita [GTK2/3]
        .oossssso-````/ossssss+`         Icons: Adwaita [GTK2/3]
       -osssssso.      :ssssssso.        Terminal: WezTerm
      :osssssss/        osssso+++.       CPU: Intel i5-1035G1 (8) @ 3.600GHz
     /ossssssss/        +ssssooo/-       GPU: Intel Iris Plus Graphics G1
   `/ossssso+/:-        -:/+osssso+-     GPU: NVIDIA GeForce MX110
  `+sso+:-`                 `.-/+oso:    Memory: 3690MiB / 15785MiB
 `++:.                           `-/+/
 .`                                 `/

```

**Comment by axetroy** [comment] 2022-03-17 18:05
The video is broken

Could you run the following command copy output here?

```bash
$ uname -s
$ uname -m
```

**Comment by UltiRequiem** [comment] 2022-03-17 18:07
> The video is broken

Weird, here it works.

> Could you run the following command copy output here?
> 
> ```shell
> $ uname -s
> $ uname -m
> ```

1. x86_64

2. Linux

**Comment by axetroy** [comment] 2022-03-18 02:02
It seems that there is no permission to decompress the file to `/usr/local/bin`.

Could you make sure have permission for this?

and I have added a ci for testing the install script, and it works fine.

https://github.com/axetroy/cask.rs/runs/5594860593?check_suite_focus=true

**Comment by UltiRequiem** [comment] 2022-03-19 01:33
> Could you make sure have permission for this?

I think I have, this works 👇🏽 

```sh
 sudo touch /usr/local/bin/hehe
```

**Comment by axetroy** [comment] 2022-03-19 01:50
Ham ... 

try unpack the tarball

```bash
tar -xz -f cask.tar.gz -C /usr/local/bin
```

I can't reproduce it, if you can help me fix it, it will be excellent.

**Comment by UltiRequiem** [comment] 2022-03-21 03:12
> Ham ...
> 
> try unpack the tarball
> 
> ```shell
> tar -xz -f cask.tar.gz -C /usr/local/bin
> ```
> 
> I can't reproduce it, if you can help me fix it, it will be excellent.

Sorry for the late response!

![image](https://user-images.githubusercontent.com/71897736/159200538-318df8b0-5f52-4000-b24e-dd302a5e6730.png)

That works!

**Comment by UltiRequiem** [comment] 2022-03-21 03:16
Just installed dvm with this installation, is really cool!

**Comment by axetroy** [comment] 2022-03-22 14:33
As Cask releases the versions of the platform, the installation script is not ensured to works on all platforms.

I close this Issue, waiting for someone specific platform feedback.

Thanks for your feeback

**Closed as completed by axetroy** 2022-03-22 14:33 UTC
